#!/usr/bin/env bash
# Smoke tests for the unified `claude-bridge` dispatcher CLI.
# Note: we deliberately use `set -eo pipefail` (no -u). The dispatcher itself
# uses `set -u`, but invoking it through a pipe under `set -u` in *some*
# sandboxed CI environments (where bash sources a shell-init snapshot that
# probes `ZSH_VERSION`) is enough to abort the parent. End-user shells don't
# have that probe; this is purely a harness compatibility shim.
set -eo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI="$ROOT/bin/claude-bridge"

TMP="$(mktemp -d -t claude-bridge-cli-test.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

BRIDGE="$TMP/bridge"
export CLAUDE_BRIDGE_DIR="$BRIDGE"
export CLAUDE_BRIDGE_LOG="$TMP/log"

# --- enable / status / disable ---------------------------------------------
"$CLI" enable >/dev/null
[ -f "$BRIDGE/.enabled" ] || { echo "FAIL: enable did not create .enabled"; exit 1; }
out="$("$CLI" status)"; case "$out" in *ARMED*) ;; *) echo "FAIL: status didn't say ARMED. Got: $out"; exit 1 ;; esac
"$CLI" disable >/dev/null
[ ! -f "$BRIDGE/.enabled" ] || { echo "FAIL: disable did not remove .enabled"; exit 1; }
out="$("$CLI" status)"; case "$out" in *dormant*) ;; *) echo "FAIL: status didn't say dormant. Got: $out"; exit 1 ;; esac
"$CLI" enable >/dev/null
echo "case 1 PASS: enable/disable/status round-trip"

# --- ls (empty) -------------------------------------------------------------
out="$("$CLI" ls)"
case "$out" in
  *"no tasks yet"*) ;;
  *) echo "FAIL: ls on empty bridge missing 'no tasks yet'. Got: $out"; exit 1 ;;
esac
echo "case 2 PASS: ls on empty bridge"

# --- seed a session and ls again -------------------------------------------
SID="sess-cli-$$"
mkdir -p "$BRIDGE/sessions/$SID/inbox"
printf 'waiting\n' > "$BRIDGE/sessions/$SID/status"
mkdir -p "$BRIDGE/tasks"
printf '%s' "$SID" > "$BRIDGE/tasks/build-pipeline"

out="$("$CLI" ls)"
case "$out" in
  *"build-pipeline"*"$SID"*) ;;
  *) echo "FAIL: ls didn't include task. Got: $out"; exit 1 ;;
esac
echo "case 3 PASS: ls shows registered task"

# --- show --json ------------------------------------------------------------
mkdir -p "$BRIDGE/outbox"
printf '# turn 1\nhello\n'  > "$BRIDGE/outbox/${SID}-20260101T000000Z.md"
sleep 0.05
printf '# turn 2\nworld\n'  > "$BRIDGE/outbox/${SID}-20260101T000100Z.md"

latest="$("$CLI" show build-pipeline)"
case "$latest" in
  *"turn 2"*) ;;
  *) echo "FAIL: show should print latest. Got: $latest"; exit 1 ;;
esac

all="$("$CLI" show build-pipeline --all)"
case "$all" in
  *"turn 1"*"turn 2"*) ;;
  *) echo "FAIL: show --all should include both turns. Got: $all"; exit 1 ;;
esac

js="$("$CLI" show build-pipeline --json)"
echo "$js" | jq -e '.file' >/dev/null || { echo "FAIL: show --json not valid JSON: $js"; exit 1; }
echo "case 4 PASS: show {latest, --all, --json}"

# --- cancel: drops sentinel, INDEX rebuilt ---------------------------------
"$CLI" cancel build-pipeline >/dev/null
[ -e "$BRIDGE/sessions/$SID/inbox/.cancel" ] \
  || { echo "FAIL: cancel sentinel not created"; exit 1; }
[ -f "$BRIDGE/outbox/INDEX.md" ] \
  || { echo "FAIL: INDEX not generated by cancel"; exit 1; }
echo "case 5 PASS: cancel drops .cancel and rebuilds INDEX"

# --- clean: prunes old archive entries -------------------------------------
mkdir -p "$BRIDGE/archive"
old="$BRIDGE/archive/old.md"
new="$BRIDGE/archive/new.md"
: > "$old"; : > "$new"
# Backdate the old file to 30 days ago.
touch -d "$(date -u -d '30 days ago' '+%Y-%m-%d') 00:00:00" "$old" 2>/dev/null \
  || touch -t "$(date -u -v-30d +%Y%m%d0000)" "$old" 2>/dev/null

"$CLI" clean --days 14 >/dev/null
[ ! -e "$old" ] || { echo "FAIL: 30-day-old archive entry not pruned"; ls -la "$BRIDGE/archive"; exit 1; }
[ -e "$new" ]   || { echo "FAIL: fresh archive entry was pruned"; exit 1; }
echo "case 6 PASS: clean prunes old archive entries, keeps fresh ones"

# --- unknown task error path ------------------------------------------------
if "$CLI" cancel does-not-exist 2>/dev/null; then
  echo "FAIL: cancel on unknown task should exit non-zero"; exit 1
fi
echo "case 7 PASS: cancel on unknown task fails cleanly"

# --- doctor (some FAILs allowed, must still exit) --------------------------
"$CLI" doctor >/dev/null 2>&1 || true
echo "case 8 PASS: doctor runs without crashing"

# --- version / help --------------------------------------------------------
"$CLI" version | grep -q '^claude-bridge ' || { echo "FAIL: version output"; exit 1; }
"$CLI" help    | grep -q 'USAGE'           || { echo "FAIL: help output"; exit 1; }
echo "case 9 PASS: version/help"

echo "ALL CLI TESTS PASSED"
